name: Build and Upload Frameworks

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        framework:
          [
            Auth,
            Functions,
            PostgREST,
            Realtime,
            Storage,
            Supabase,
            CCryptoBoringSSL,
            CCryptoBoringSSLShims,
            Clocks,
            ConcurrencyExtras,
            Crypto,
            CryptoBoringWrapper,
            CustomDump,
            HTTPTypes,
            Helpers,
            IssueReporting,
            Mocker,
            SwiftBasicFormat,
            SwiftDiagnostics,
            SwiftParser,
            SwiftParserDiagnostics,
            SwiftSyntax,
            SwiftSyntax509,
            SwiftSyntax600,
            SwiftSyntaxBuilder,
            XCTestDynamicOverlay,
            _SwiftSyntaxCShims,
          ]

    steps:
      - uses: actions/checkout@v4

      - name: Install create-xcframework
        run: |
          git clone https://github.com/mackoj/swift-create-xcframework/ -b bump/swift5.10
          cd swift-create-xcframework
          make install

      - name: Build ${{ matrix.framework }}.framework (Release, iOS)
        run: swift create-xcframework --platform ios ${{ matrix.framework }} --xc-setting OTHER_SWIFT_FLAGS="-package-name xctest-dynamic-overlay" --xc-setting IPHONEOS_DEPLOYMENT_TARGET=17.5 --stack-evolution

      - name: Upload ${{ matrix.framework }}.framework artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.framework }}.framework
          path: ${{ matrix.framework }}.xcframework/ios-arm64/${{ matrix.framework }}.framework
