name: Build and Upload Frameworks

on:
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        framework: [Supabase] #, Auth, Functions, PostgREST, Realtime, Storage]

    steps:
      - uses: actions/checkout@v4

      - name: Install Swift 6.0.2 toolchain
        run: |
          curl -L https://download.swift.org/swift-6.0.2-release/xcode/swift-6.0.2-RELEASE/swift-6.0.2-RELEASE-osx.pkg -o swift.pkg
          sudo installer -pkg swift.pkg -target /

      - name: Use Swift 6.0.2 toolchain
        run: echo '/Library/Developer/Toolchains/swift-6.0.2-RELEASE.xctoolchain/usr/bin' >> $GITHUB_PATH

      - name: Set Xcode to 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Build ${{ matrix.framework }}.framework (Release, iOS)
        run: bash build_framework.sh ${{ matrix.framework }}

      - name: Upload ${{ matrix.framework }}.framework artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.framework }}.framework
          path: build/${{ matrix.framework }}-iphoneos.xcarchive/Products/Library/Frameworks/${{ matrix.framework }}.framework
