name: Build and Upload Frameworks

on:
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        framework: [Supabase, Auth, Functions, PostgREST, Realtime, Storage]

    steps:
      - uses: actions/checkout@v4

      - name: Build ${{ matrix.framework }}.framework (Release, iOS)
        run: bash build_framework.sh ${{ matrix.framework }}

      - name: Upload ${{ matrix.framework }}.framework artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.framework }}.framework
          path: build/${{ matrix.framework }}-iphoneos.xcarchive/Products/Library/Frameworks/${{ matrix.framework }}.framework
