name: Build and Upload Supabase.framework

on:
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Supabase.framework (Release, iOS)
        run: |
          xcodebuild -workspace Supabase.xcworkspace -scheme Supabase -sdk iphoneos -configuration Release build

      - name: Find Supabase.framework path
        id: find_framework
        run: |
          FRAMEWORK_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "Supabase.framework" | head -n 1)
          echo "Supabase.framework path: $FRAMEWORK_PATH"
          echo "FRAMEWORK_PATH=$FRAMEWORK_PATH" >> $GITHUB_ENV

      - name: Upload Supabase.framework artifact
        uses: actions/upload-artifact@v4
        with:
          name: Supabase.framework
          path: ${{ env.FRAMEWORK_PATH }}
