name: Build and Upload Supabase.framework

on:
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Supabase.framework (Release, iOS)
        run: bash build_framework.sh Supabase

      - name: Build Auth.framework (Release, iOS)
        run: bash build_framework.sh Auth

      - name: Upload Supabase.framework artifact
        uses: actions/upload-artifact@v4
        with:
          name: Supabase.framework
          path: build/Supabase-iphoneos.xcarchive/Products/Library/Frameworks/Supabase.framework

      - name: Upload Auth.framework artifact
        uses: actions/upload-artifact@v4
        with:
          name: Auth.framework
          path: build/Auth-iphoneos.xcarchive/Products/Library/Frameworks/Auth.framework
