name: Build SupabaseSwift Framework

on:
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Build Framework (Release, iOS)
        run: |
          xcodebuild -scheme Supabase -sdk iphoneos -configuration Release -destination 'generic/platform=iOS' -archivePath $PWD/build/SupabaseSwift.xcarchive archive
      
      - name: Copy Framework from Archive
        run: |
          mkdir -p output
          cp -R build/SupabaseSwift.xcarchive/Products/Library/Frameworks/Supabase.framework output/
      
      - name: Upload Framework Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Supabase.framework
          path: output/Supabase.framework
